language: node_js
sudo: required
dist: trusty
node_js:
  - '6'

cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#      - google-chrome // only needed if testing with Karma
#    packages:
#      - google-chrome-stable
env:
 - CXX=g++-4.8
 - g++-4.8
 - NPM_VERSION=3
 - TRAVIS_NODE_VERSION="6"
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  - sudo apt-get update -qq
  # Log HTTP requests
  - npm config set loglevel http
  # Install npm dependencies and ensure that npm cache is not stale
  - npm install
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  email: true

script:
  - npm test
  - npm run coverage:report
after_script:
# Upload to coveralls, but don't _fail_ if coveralls is down.
#  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
#  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
